### PR TITLE
Added Belarus language

### PR DESCRIPTION
**Pull request by bykidi**
Not sure about the lang code in header.php, correct me if i'm wrong.

### CODE REVIEW

**Comment by Wruczek** [comment]
Thank you! Looks good, and the language code is correct. But can you maybe restore the formatting (new lines) in the lang file? That way it will be easier to read and edit. [A good example](/Wruczek/ts-website/blob/master/config/languages/lang.en.php) of how it should look.

**Comment by bykidi** [comment]
Something is wrong here
default
But overall language is working fine. Perhabs i should clean cache...

**Comment by Wruczek** [comment]
Woks for me - check your file encoding.

image

**Comment by Wruczek** [comment]
Thanks - merged!

**Comment by bykidi** [comment]
Yup!
default

**Pull request merged**
