### PR TITLE
Added French language (Thanks FleuryK!)

### PR DESCRIPTION
**Pull request by FleuryK**
Hello,

I watched your demo. Congratulations on your work.
Unfortunately, there was not (until I landed) the French language.

Today I propose to you the addition of the French language for the Francophone users with those already existing.

Hopefully he will be present at the next update.

See you soon.

### CODE REVIEW

**Comment by Wruczek** [comment]
Thank you! Looking good, but can you maybe transform the html chars to their values? It will make it easier for other people to edit.

For example:
HTML char | Value
------------ | -------------
`&#039;` | '
`&egrave;` | è
`&agrave;` | à

**Comment by Wruczek** [comment]
Also: can you add it to [the header](https://github.com/Wruczek/ts-website/blob/master/include/header.php#L109)?

**Comment by FleuryK** [comment]
Hello,

Oops, I forgot to edit this file.
I have edited file on the new pull request.

For your question: I usually put in hexadecimal. Sorry.

See You Soon.

**Comment by Wruczek** [comment]
So will you make another pull request or should I change it myself?

**Comment by Wruczek** [comment]
Ok, changed in #21. Thanks!

**Pull request merged**
