### PR TITLE
Small update

### PR DESCRIPTION
**Pull request by toster234**
Set max height and width to 16 x 16

### CODE REVIEW

**Comment by Wruczek** [comment]
Unfortunately it will not fix all the problems with 3.1.5 icons, but I can merge it just to fix the adminlist icons. Can you also change the version in `modulecheck.php`?

**Comment by avsaponchik** [comment]
OFFTOPIC: @Wruczek what's the state on V2.0?

**Comment by Wruczek** [comment]
@bykidi Its going forward, around 60% of it is already done. It took me way much time than I've expected, but now that the major features are done Im expecting the release at the beginning of the next month. I will post updates on Telegram group if you are interested, or can always message me here on Telegram ;)

**Comment by Wruczek** [comment]
Fixed with 8ab147cdcbdbe87915f7cac7c102096f0e6ff332

**Pull request closed without merging**
